# Evozon Magento 2 Setup with Docker Compose
# Copyright (c) 2017 Evozon-PHP

version: "3"

services:
  app:
    build:
      context: .docker/nginx/
    image: evozon/magento2-nginx
    container_name: evozon_magento2_nginx
    depends_on: 
      - db
      - phpfpm
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ./html:/var/www/html
      - ./.composer:/var/www/.composer
    ports:
      - 80:80
    networks: &appnetworks
      - www

  phpfpm:
    build:
      context: .docker/php/
    image: evozon/magento2-php
    container_name: evozon_magento2_php
    depends_on: 
      - db
    links:
      - db
    volumes: *appvolumes
    networks: *appnetworks
    env_file: .env/setup.env

  db:
    image: percona:5.7
    volumes:
      - ./dbdata/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks: *appnetworks
    env_file: .env/mysql.env
 
  setup:
    image: evozon/magento2-php
    command: /usr/local/bin/mage-setup
    links:
      - db
    volumes: *appvolumes
    networks: *appnetworks
    env_file: .env/setup.env

networks:
  www:
